# -*- coding: utf-8 -*-
"""healthcare and clinical data analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rRmJ1E3jM63qnL2TKmBKsKwvilQwnrB2
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

patients = pd.read_csv("patients.csv")
encounters = pd.read_csv("encounters.csv")
labs = pd.read_csv("labs.csv")
diagnoses = pd.read_csv("diagnoses.csv")
medications = pd.read_csv("medications.csv")
data_dictionary = pd.read_csv("data_dictionary.csv")

print("Patients:", patients.shape)
print("Encounters:", encounters.shape)
print("Labs:", labs.shape)
print("Diagnoses:", diagnoses.shape)
print("Medications:", medications.shape)
print("Data Dictionary:", data_dictionary.shape)

#Checking data types and missing values
datasets = {
    "patients": patients,
    "encounters": encounters,
    "labs": labs,
    "diagnoses": diagnoses,
    "medications": medications
}

for name, df in datasets.items():
    print(f"\n{name.upper()}")
    print(df.dtypes)
    print("\nMissing values:")
    print(df.isna().sum())

#Converting date columns
encounters["Encounter_Date"] = pd.to_datetime(encounters["Encounter_Date"])
labs["Lab_Date"] = pd.to_datetime(labs["Lab_Date"])
diagnoses["Diagnosis_Date"] = pd.to_datetime(diagnoses["Diagnosis_Date"])
medications["Medication_Date"] = pd.to_datetime(medications["Medication_Date"])

print(encounters["Encounter_Date"].dtype)
print(labs["Lab_Date"].dtype)
print(diagnoses["Diagnosis_Date"].dtype)
print(medications["Medication_Date"].dtype)

#Creating analysis-ready clean datasets
patients_clean = patients[
    patients["Gender"] != "Unknown"
].copy()

encounters_clean = encounters[
    encounters["Outcome"] != "Unknown"
].copy()

diagnoses_clean = diagnoses[
    diagnoses["Diagnosis_Code"] != "UNK"
].copy()

labs_clean = labs[
    labs["Result_Value"].notna()
].copy()

# Useful time fields
encounters_clean["Year"] = encounters_clean["Encounter_Date"].dt.year
encounters_clean["Month"] = encounters_clean["Encounter_Date"].dt.month
encounters_clean["Year_Month"] = encounters_clean["Encounter_Date"].dt.to_period("M").astype(str)

labs_clean["Year"] = labs_clean["Lab_Date"].dt.year
labs_clean["Year_Month"] = labs_clean["Lab_Date"].dt.to_period("M").astype(str)

print("Patients clean:", patients_clean.shape)
print("Encounters clean:", encounters_clean.shape)
print("Labs clean:", labs_clean.shape)
print("Diagnoses clean:", diagnoses_clean.shape)

#Patient population analysis
patient_summary = {
    "Total Patients": len(patients),
    "Average Age": round(patients["Age"].mean(), 1),
    "Female Patients": (patients_clean["Gender"] == "Female").sum(),
    "Male Patients": (patients_clean["Gender"] == "Male").sum(),
    "High Risk Patients": (patients["Risk_Category"] == "High").sum(),
    "Medium Risk Patients": (patients["Risk_Category"] == "Medium").sum(),
    "Low Risk Patients": (patients["Risk_Category"] == "Low").sum()
}

patient_summary

#Visualize patient distribution by primary condition
condition_counts = (
    patients_clean["Primary_Condition"]
    .value_counts()
    .sort_values(ascending=True)
)

plt.figure(figsize=(10, 6))

plt.barh(
    condition_counts.index,
    condition_counts.values, color=sns.color_palette("Greens_r", len(condition_counts))
)

plt.title("Patient Distribution by Primary Condition")
plt.xlabel("Number of Patients")
plt.ylabel("Primary Condition")

plt.tight_layout()
plt.show()

#Risk category visualization
risk_counts = (
    patients_clean["Risk_Category"]
    .value_counts()
    .reindex(["Low", "Medium", "High"])
)

plt.figure(figsize=(8, 5))

plt.bar(
    risk_counts.index,
    risk_counts.values, color=sns.color_palette("Greens_r", len(risk_counts))
)

plt.title("Patient Distribution by Risk Category")
plt.xlabel("Risk Category")
plt.ylabel("Number of Patients")

plt.tight_layout()
plt.show()

#Encounter utilization analysis
encounter_counts = (
    encounters_clean["Encounter_Type"]
    .value_counts()
    .sort_values(ascending=True)
)

plt.figure(figsize=(9, 5))

plt.barh(
    encounter_counts.index,
    encounter_counts.values, color=sns.color_palette("Greens_r", len(encounter_counts))
)

plt.title("Healthcare Encounters by Encounter Type")
plt.xlabel("Number of Encounters")
plt.ylabel("Encounter Type")

plt.tight_layout()
plt.show()

#Encounter outcomes visualization
outcome_counts = (
    encounters_clean["Outcome"]
    .value_counts()
    .sort_values(ascending=True)
)

plt.figure(figsize=(9, 5))

plt.barh(
    outcome_counts.index,
    outcome_counts.values, color=sns.color_palette("Greens_r", len(outcome_counts))
)

plt.title("Healthcare Encounter Outcomes")
plt.xlabel("Number of Encounters")
plt.ylabel("Outcome")

plt.tight_layout()
plt.show()

#Monthly encounter trend
monthly_trend = (
    encounters_clean
    .groupby("Year_Month")
    .size()
)

plt.figure(figsize=(12, 5))

plt.plot(
    monthly_trend.index,
    monthly_trend.values, color='Green'
)

plt.title("Monthly Healthcare Encounter Volume")
plt.xlabel("Month")
plt.ylabel("Number of Encounters")

plt.xticks(
    monthly_trend.index[::3],
    rotation=45
)

plt.tight_layout()
plt.show()

#Compare laboratory result distributions
lab_plot = labs_clean.copy()

lab_plot["Standardized_Result"] = (
    lab_plot.groupby("Test_Name")["Result_Value"]
    .transform(lambda x: (x - x.mean()) / x.std())
)

lab_order = [
    "HbA1c",
    "Glucose",
    "Creatinine",
    "Hemoglobin",
    "LDL Cholesterol",
    "Systolic BP"
]

plt.figure(figsize=(11, 6))

sns.boxplot(
    data=lab_plot,
    x="Test_Name",
    y="Standardized_Result",
    order=lab_order, color='Green'
)

plt.title("Standardized Laboratory Result Distributions")
plt.xlabel("Laboratory Test")
plt.ylabel("Standardized Result (Z-score)")
plt.xticks(rotation=30)

plt.tight_layout()
plt.show()

#High-utilization heatmap
patient_utilization = (
    encounters
    .groupby("Patient_ID")
    .size()
    .reset_index(name="Encounter_Count")
)

utilization_analysis = patients.copy()

utilization_analysis = utilization_analysis.merge(
    patient_utilization,
    on="Patient_ID",
    how="left"
)

utilization_analysis["Encounter_Count"] = (
    utilization_analysis["Encounter_Count"]
    .fillna(0)
)

utilization_analysis["High_Utilization"] = (
    utilization_analysis["Encounter_Count"] >= 6
)

heatmap_data = (
    utilization_analysis
    .groupby(["Risk_Category", "Primary_Condition"])["High_Utilization"]
    .mean()
    .unstack()
    .mul(100)
)

heatmap_data = heatmap_data.reindex(
    ["High", "Medium", "Low"]
)

plt.figure(figsize=(11, 6))

sns.heatmap(
    heatmap_data,
    annot=True,
    fmt=".1f",  cmap="Greens"
)

plt.title("High-Utilization Rate by Risk Category and Primary Condition")
plt.xlabel("Primary Condition")
plt.ylabel("Risk Category")

plt.tight_layout()
plt.show()

#Diagnosis prevalence
diagnosis_counts = (
    diagnoses_clean["Diagnosis_Name"]
    .value_counts()
    .sort_values(ascending=True)
)

plt.figure(figsize=(10, 6))

plt.barh(
    diagnosis_counts.index,
    diagnosis_counts.values, color=sns.color_palette("Greens_r", len(diagnosis_counts))
)

plt.title("Recorded Diagnoses by Diagnosis Type")
plt.xlabel("Number of Diagnosis Records")
plt.ylabel("Diagnosis")

plt.tight_layout()
plt.show()

#Medication utilization
medication_counts = (
    medications["Medication_Name"]
    .value_counts()
    .sort_values(ascending=True)
)

plt.figure(figsize=(10, 6))

plt.barh(
    medication_counts.index,
    medication_counts.values, color=sns.color_palette("Greens_r", len(medication_counts))
)

plt.title("Medication Utilization by Medication")
plt.xlabel("Number of Medication Records")
plt.ylabel("Medication")

plt.tight_layout()
plt.show()

#Python summary

high_utilization_count = (
    utilization_analysis["High_Utilization"].sum()
)

final_summary = pd.DataFrame({
    "Metric": [
        "Total Patients",
        "Average Age",
        "Total Encounters",
        "Average Encounters per Patient",
        "Emergency Encounter Rate",
        "Inpatient Encounter Rate",
        "Improvement Rate",
        "Worsening Rate",
        "High-Utilization Patients",
        "High-Utilization Rate",
        "Laboratory Records",
        "Missing Laboratory Results",
        "Diagnosis Records",
        "Medication Records"
    ],
    "Value": [
        len(patients),
        round(patients["Age"].mean(), 1),
        len(encounters),
        round(encounters["Patient_ID"].count() / encounters["Patient_ID"].nunique(), 2),
        round((encounters["Encounter_Type"] == "Emergency").mean() * 100, 2),
        round((encounters["Encounter_Type"] == "Inpatient").mean() * 100, 2),
        round((encounters_clean["Outcome"] == "Improved").mean() * 100, 2),
        round((encounters_clean["Outcome"] == "Worsened").mean() * 100, 2),
        high_utilization_count,
        round(high_utilization_count / len(patients) * 100, 2),
        len(labs),
        labs["Result_Value"].isna().sum(),
        len(diagnoses),
        len(medications)
    ]
})

print(final_summary)

final_summary.to_csv(
    "healthcare_clinical_analysis_summary.csv",
    index=False
)

#powerbi dataset preparation
# Create patient-level utilization metrics
patient_utilization = (
    encounters
    .groupby("Patient_ID")
    .agg(
        Encounter_Count=("Encounter_ID", "count"),
        Emergency_Encounters=("Encounter_Type", lambda x: (x == "Emergency").sum()),
        Inpatient_Encounters=("Encounter_Type", lambda x: (x == "Inpatient").sum())
    )
    .reset_index()
)

# Create diagnosis count per patient
patient_diagnosis = (
    diagnoses_clean
    .groupby("Patient_ID")
    .agg(
        Distinct_Diagnoses=("Diagnosis_Code", "nunique")
    )
    .reset_index()
)

# Create medication metrics per patient
patient_medication = (
    medications
    .groupby("Patient_ID")
    .agg(
        Medication_Records=("Medication_ID", "count"),
        Active_Medications=("Medication_Status", lambda x: (x == "Active").sum())
    )
    .reset_index()
)

# Enrich encounters with patient information
powerbi_data = (
    encounters
    .merge(
        patients_clean,
        on="Patient_ID",
        how="left"
    )
    .merge(
        patient_utilization,
        on="Patient_ID",
        how="left"
    )
    .merge(
        patient_diagnosis,
        on="Patient_ID",
        how="left"
    )
    .merge(
        patient_medication,
        on="Patient_ID",
        how="left"
    )
)

# High-utilization classification
powerbi_data["High_Utilization"] = (
    powerbi_data["Encounter_Count"] >= 6
)

print("Power BI dataset shape:", powerbi_data.shape)
print("\nColumns:")
print(powerbi_data.columns.tolist())

powerbi_data.to_csv(
    "encounters_enriched.csv",
    index=False
)

print("Export complete")
print("Rows:", len(powerbi_data))
print("Columns:", len(powerbi_data.columns))



